# Generated by Django 3.0.3 on 2020-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daoink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='storage_uri',
            field=models.CharField(max_length=255, verbose_name='文件存储URI'),
        ),
    ]
