# Generated by Django 3.0.3 on 2020-02-26 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daoink', '0002_auto_20200225_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tel',
            new_name='phone_number',
        ),
    ]
